language: go
go:
 - 1.11
 - 1.12
install:
 - go get github.com/golang/lint/golint
 - go get github.com/fzipp/gocyclo
 - go get github.com/client9/misspell/...
 - go get github.com/gordonklaus/ineffassign
 - go get -d ...  # Downloads all the dependencies of naffka
script: ./hooks/pre-commit
