language: go
go:
 - 1.8
install:
 - go get github.com/golang/lint/golint
 - go get github.com/fzipp/gocyclo
 - go get github.com/client9/misspell/...
 - go get github.com/gordonklaus/ineffassign
 - go get gopkg.in/Shopify/sarama.v1
script: ./hooks/pre-commit
